/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type BackfillErrorCode string

const (
	BackfillErrorCode_ENCRYPTED_PARTITION_ERROR             BackfillErrorCode = "ENCRYPTED_PARTITION_ERROR"
	BackfillErrorCode_INTERNAL_ERROR                        BackfillErrorCode = "INTERNAL_ERROR"
	BackfillErrorCode_INVALID_PARTITION_TYPE_DATA_ERROR     BackfillErrorCode = "INVALID_PARTITION_TYPE_DATA_ERROR"
	BackfillErrorCode_MISSING_PARTITION_VALUE_ERROR         BackfillErrorCode = "MISSING_PARTITION_VALUE_ERROR"
	BackfillErrorCode_UNSUPPORTED_PARTITION_CHARACTER_ERROR BackfillErrorCode = "UNSUPPORTED_PARTITION_CHARACTER_ERROR"
)

type BlueprintRunState string

const (
	BlueprintRunState_RUNNING      BlueprintRunState = "RUNNING"
	BlueprintRunState_SUCCEEDED    BlueprintRunState = "SUCCEEDED"
	BlueprintRunState_FAILED       BlueprintRunState = "FAILED"
	BlueprintRunState_ROLLING_BACK BlueprintRunState = "ROLLING_BACK"
)

type BlueprintStatus string

const (
	BlueprintStatus_CREATING BlueprintStatus = "CREATING"
	BlueprintStatus_ACTIVE   BlueprintStatus = "ACTIVE"
	BlueprintStatus_UPDATING BlueprintStatus = "UPDATING"
	BlueprintStatus_FAILED   BlueprintStatus = "FAILED"
)

type CatalogEncryptionMode string

const (
	CatalogEncryptionMode_DISABLED CatalogEncryptionMode = "DISABLED"
	CatalogEncryptionMode_SSE_KMS  CatalogEncryptionMode = "SSE-KMS"
)

type CloudWatchEncryptionMode string

const (
	CloudWatchEncryptionMode_DISABLED CloudWatchEncryptionMode = "DISABLED"
	CloudWatchEncryptionMode_SSE_KMS  CloudWatchEncryptionMode = "SSE-KMS"
)

type ColumnStatisticsType string

const (
	ColumnStatisticsType_BOOLEAN ColumnStatisticsType = "BOOLEAN"
	ColumnStatisticsType_DATE    ColumnStatisticsType = "DATE"
	ColumnStatisticsType_DECIMAL ColumnStatisticsType = "DECIMAL"
	ColumnStatisticsType_DOUBLE  ColumnStatisticsType = "DOUBLE"
	ColumnStatisticsType_LONG    ColumnStatisticsType = "LONG"
	ColumnStatisticsType_STRING  ColumnStatisticsType = "STRING"
	ColumnStatisticsType_BINARY  ColumnStatisticsType = "BINARY"
)

type Comparator string

const (
	Comparator_EQUALS              Comparator = "EQUALS"
	Comparator_GREATER_THAN        Comparator = "GREATER_THAN"
	Comparator_LESS_THAN           Comparator = "LESS_THAN"
	Comparator_GREATER_THAN_EQUALS Comparator = "GREATER_THAN_EQUALS"
	Comparator_LESS_THAN_EQUALS    Comparator = "LESS_THAN_EQUALS"
)

type Compatibility string

const (
	Compatibility_NONE         Compatibility = "NONE"
	Compatibility_DISABLED     Compatibility = "DISABLED"
	Compatibility_BACKWARD     Compatibility = "BACKWARD"
	Compatibility_BACKWARD_ALL Compatibility = "BACKWARD_ALL"
	Compatibility_FORWARD      Compatibility = "FORWARD"
	Compatibility_FORWARD_ALL  Compatibility = "FORWARD_ALL"
	Compatibility_FULL         Compatibility = "FULL"
	Compatibility_FULL_ALL     Compatibility = "FULL_ALL"
)

type ConnectionPropertyKey string

const (
	ConnectionPropertyKey_HOST                                     ConnectionPropertyKey = "HOST"
	ConnectionPropertyKey_PORT                                     ConnectionPropertyKey = "PORT"
	ConnectionPropertyKey_USERNAME                                 ConnectionPropertyKey = "USERNAME"
	ConnectionPropertyKey_PASSWORD                                 ConnectionPropertyKey = "PASSWORD"
	ConnectionPropertyKey_ENCRYPTED_PASSWORD                       ConnectionPropertyKey = "ENCRYPTED_PASSWORD"
	ConnectionPropertyKey_JDBC_DRIVER_JAR_URI                      ConnectionPropertyKey = "JDBC_DRIVER_JAR_URI"
	ConnectionPropertyKey_JDBC_DRIVER_CLASS_NAME                   ConnectionPropertyKey = "JDBC_DRIVER_CLASS_NAME"
	ConnectionPropertyKey_JDBC_ENGINE                              ConnectionPropertyKey = "JDBC_ENGINE"
	ConnectionPropertyKey_JDBC_ENGINE_VERSION                      ConnectionPropertyKey = "JDBC_ENGINE_VERSION"
	ConnectionPropertyKey_CONFIG_FILES                             ConnectionPropertyKey = "CONFIG_FILES"
	ConnectionPropertyKey_INSTANCE_ID                              ConnectionPropertyKey = "INSTANCE_ID"
	ConnectionPropertyKey_JDBC_CONNECTION_URL                      ConnectionPropertyKey = "JDBC_CONNECTION_URL"
	ConnectionPropertyKey_JDBC_ENFORCE_SSL                         ConnectionPropertyKey = "JDBC_ENFORCE_SSL"
	ConnectionPropertyKey_CUSTOM_JDBC_CERT                         ConnectionPropertyKey = "CUSTOM_JDBC_CERT"
	ConnectionPropertyKey_SKIP_CUSTOM_JDBC_CERT_VALIDATION         ConnectionPropertyKey = "SKIP_CUSTOM_JDBC_CERT_VALIDATION"
	ConnectionPropertyKey_CUSTOM_JDBC_CERT_STRING                  ConnectionPropertyKey = "CUSTOM_JDBC_CERT_STRING"
	ConnectionPropertyKey_CONNECTION_URL                           ConnectionPropertyKey = "CONNECTION_URL"
	ConnectionPropertyKey_KAFKA_BOOTSTRAP_SERVERS                  ConnectionPropertyKey = "KAFKA_BOOTSTRAP_SERVERS"
	ConnectionPropertyKey_KAFKA_SSL_ENABLED                        ConnectionPropertyKey = "KAFKA_SSL_ENABLED"
	ConnectionPropertyKey_KAFKA_CUSTOM_CERT                        ConnectionPropertyKey = "KAFKA_CUSTOM_CERT"
	ConnectionPropertyKey_KAFKA_SKIP_CUSTOM_CERT_VALIDATION        ConnectionPropertyKey = "KAFKA_SKIP_CUSTOM_CERT_VALIDATION"
	ConnectionPropertyKey_KAFKA_CLIENT_KEYSTORE                    ConnectionPropertyKey = "KAFKA_CLIENT_KEYSTORE"
	ConnectionPropertyKey_KAFKA_CLIENT_KEYSTORE_PASSWORD           ConnectionPropertyKey = "KAFKA_CLIENT_KEYSTORE_PASSWORD"
	ConnectionPropertyKey_KAFKA_CLIENT_KEY_PASSWORD                ConnectionPropertyKey = "KAFKA_CLIENT_KEY_PASSWORD"
	ConnectionPropertyKey_ENCRYPTED_KAFKA_CLIENT_KEYSTORE_PASSWORD ConnectionPropertyKey = "ENCRYPTED_KAFKA_CLIENT_KEYSTORE_PASSWORD"
	ConnectionPropertyKey_ENCRYPTED_KAFKA_CLIENT_KEY_PASSWORD      ConnectionPropertyKey = "ENCRYPTED_KAFKA_CLIENT_KEY_PASSWORD"
	ConnectionPropertyKey_SECRET_ID                                ConnectionPropertyKey = "SECRET_ID"
	ConnectionPropertyKey_CONNECTOR_URL                            ConnectionPropertyKey = "CONNECTOR_URL"
	ConnectionPropertyKey_CONNECTOR_TYPE                           ConnectionPropertyKey = "CONNECTOR_TYPE"
	ConnectionPropertyKey_CONNECTOR_CLASS_NAME                     ConnectionPropertyKey = "CONNECTOR_CLASS_NAME"
)

type ConnectionType string

const (
	ConnectionType_JDBC        ConnectionType = "JDBC"
	ConnectionType_SFTP        ConnectionType = "SFTP"
	ConnectionType_MONGODB     ConnectionType = "MONGODB"
	ConnectionType_KAFKA       ConnectionType = "KAFKA"
	ConnectionType_NETWORK     ConnectionType = "NETWORK"
	ConnectionType_MARKETPLACE ConnectionType = "MARKETPLACE"
	ConnectionType_CUSTOM      ConnectionType = "CUSTOM"
)

type CrawlState string

const (
	CrawlState_RUNNING    CrawlState = "RUNNING"
	CrawlState_CANCELLING CrawlState = "CANCELLING"
	CrawlState_CANCELLED  CrawlState = "CANCELLED"
	CrawlState_SUCCEEDED  CrawlState = "SUCCEEDED"
	CrawlState_FAILED     CrawlState = "FAILED"
)

type CrawlerLineageSettings string

const (
	CrawlerLineageSettings_ENABLE  CrawlerLineageSettings = "ENABLE"
	CrawlerLineageSettings_DISABLE CrawlerLineageSettings = "DISABLE"
)

type CrawlerState string

const (
	CrawlerState_READY    CrawlerState = "READY"
	CrawlerState_RUNNING  CrawlerState = "RUNNING"
	CrawlerState_STOPPING CrawlerState = "STOPPING"
)

type CsvHeaderOption string

const (
	CsvHeaderOption_UNKNOWN CsvHeaderOption = "UNKNOWN"
	CsvHeaderOption_PRESENT CsvHeaderOption = "PRESENT"
	CsvHeaderOption_ABSENT  CsvHeaderOption = "ABSENT"
)

type DataFormat string

const (
	DataFormat_AVRO DataFormat = "AVRO"
	DataFormat_JSON DataFormat = "JSON"
)

type DeleteBehavior string

const (
	DeleteBehavior_LOG                   DeleteBehavior = "LOG"
	DeleteBehavior_DELETE_FROM_DATABASE  DeleteBehavior = "DELETE_FROM_DATABASE"
	DeleteBehavior_DEPRECATE_IN_DATABASE DeleteBehavior = "DEPRECATE_IN_DATABASE"
)

type EnableHybridValues string

const (
	EnableHybridValues_TRUE  EnableHybridValues = "TRUE"
	EnableHybridValues_FALSE EnableHybridValues = "FALSE"
)

type ExistCondition string

const (
	ExistCondition_MUST_EXIST ExistCondition = "MUST_EXIST"
	ExistCondition_NOT_EXIST  ExistCondition = "NOT_EXIST"
	ExistCondition_NONE       ExistCondition = "NONE"
)

type JobBookmarksEncryptionMode string

const (
	JobBookmarksEncryptionMode_DISABLED JobBookmarksEncryptionMode = "DISABLED"
	JobBookmarksEncryptionMode_CSE_KMS  JobBookmarksEncryptionMode = "CSE-KMS"
)

type JobRunState string

const (
	JobRunState_STARTING  JobRunState = "STARTING"
	JobRunState_RUNNING   JobRunState = "RUNNING"
	JobRunState_STOPPING  JobRunState = "STOPPING"
	JobRunState_STOPPED   JobRunState = "STOPPED"
	JobRunState_SUCCEEDED JobRunState = "SUCCEEDED"
	JobRunState_FAILED    JobRunState = "FAILED"
	JobRunState_TIMEOUT   JobRunState = "TIMEOUT"
)

type Language string

const (
	Language_PYTHON Language = "PYTHON"
	Language_SCALA  Language = "SCALA"
)

type LastCrawlStatus string

const (
	LastCrawlStatus_SUCCEEDED LastCrawlStatus = "SUCCEEDED"
	LastCrawlStatus_CANCELLED LastCrawlStatus = "CANCELLED"
	LastCrawlStatus_FAILED    LastCrawlStatus = "FAILED"
)

type Logical string

const (
	Logical_AND Logical = "AND"
	Logical_ANY Logical = "ANY"
)

type LogicalOperator string

const (
	LogicalOperator_EQUALS LogicalOperator = "EQUALS"
)

type MLUserDataEncryptionModeString string

const (
	MLUserDataEncryptionModeString_DISABLED MLUserDataEncryptionModeString = "DISABLED"
	MLUserDataEncryptionModeString_SSE_KMS  MLUserDataEncryptionModeString = "SSE-KMS"
)

type NodeType string

const (
	NodeType_CRAWLER NodeType = "CRAWLER"
	NodeType_JOB     NodeType = "JOB"
	NodeType_TRIGGER NodeType = "TRIGGER"
)

type PartitionIndexStatus string

const (
	PartitionIndexStatus_CREATING PartitionIndexStatus = "CREATING"
	PartitionIndexStatus_ACTIVE   PartitionIndexStatus = "ACTIVE"
	PartitionIndexStatus_DELETING PartitionIndexStatus = "DELETING"
	PartitionIndexStatus_FAILED   PartitionIndexStatus = "FAILED"
)

type Permission string

const (
	Permission_ALL                  Permission = "ALL"
	Permission_SELECT               Permission = "SELECT"
	Permission_ALTER                Permission = "ALTER"
	Permission_DROP                 Permission = "DROP"
	Permission_DELETE               Permission = "DELETE"
	Permission_INSERT               Permission = "INSERT"
	Permission_CREATE_DATABASE      Permission = "CREATE_DATABASE"
	Permission_CREATE_TABLE         Permission = "CREATE_TABLE"
	Permission_DATA_LOCATION_ACCESS Permission = "DATA_LOCATION_ACCESS"
)

type PrincipalType string

const (
	PrincipalType_USER  PrincipalType = "USER"
	PrincipalType_ROLE  PrincipalType = "ROLE"
	PrincipalType_GROUP PrincipalType = "GROUP"
)

type RecrawlBehavior string

const (
	RecrawlBehavior_CRAWL_EVERYTHING       RecrawlBehavior = "CRAWL_EVERYTHING"
	RecrawlBehavior_CRAWL_NEW_FOLDERS_ONLY RecrawlBehavior = "CRAWL_NEW_FOLDERS_ONLY"
	RecrawlBehavior_CRAWL_EVENT_MODE       RecrawlBehavior = "CRAWL_EVENT_MODE"
)

type RegistryStatus string

const (
	RegistryStatus_AVAILABLE RegistryStatus = "AVAILABLE"
	RegistryStatus_DELETING  RegistryStatus = "DELETING"
)

type ResourceShareType string

const (
	ResourceShareType_FOREIGN ResourceShareType = "FOREIGN"
	ResourceShareType_ALL     ResourceShareType = "ALL"
)

type ResourceType string

const (
	ResourceType_JAR     ResourceType = "JAR"
	ResourceType_FILE    ResourceType = "FILE"
	ResourceType_ARCHIVE ResourceType = "ARCHIVE"
)

type S3EncryptionMode string

const (
	S3EncryptionMode_DISABLED S3EncryptionMode = "DISABLED"
	S3EncryptionMode_SSE_KMS  S3EncryptionMode = "SSE-KMS"
	S3EncryptionMode_SSE_S3   S3EncryptionMode = "SSE-S3"
)

type ScheduleState string

const (
	ScheduleState_SCHEDULED     ScheduleState = "SCHEDULED"
	ScheduleState_NOT_SCHEDULED ScheduleState = "NOT_SCHEDULED"
	ScheduleState_TRANSITIONING ScheduleState = "TRANSITIONING"
)

type SchemaDiffType string

const (
	SchemaDiffType_SYNTAX_DIFF SchemaDiffType = "SYNTAX_DIFF"
)

type SchemaStatus string

const (
	SchemaStatus_AVAILABLE SchemaStatus = "AVAILABLE"
	SchemaStatus_PENDING   SchemaStatus = "PENDING"
	SchemaStatus_DELETING  SchemaStatus = "DELETING"
)

type SchemaVersionStatus string

const (
	SchemaVersionStatus_AVAILABLE SchemaVersionStatus = "AVAILABLE"
	SchemaVersionStatus_PENDING   SchemaVersionStatus = "PENDING"
	SchemaVersionStatus_FAILURE   SchemaVersionStatus = "FAILURE"
	SchemaVersionStatus_DELETING  SchemaVersionStatus = "DELETING"
)

type Sort string

const (
	Sort_ASC  Sort = "ASC"
	Sort_DESC Sort = "DESC"
)

type SortDirectionType string

const (
	SortDirectionType_DESCENDING SortDirectionType = "DESCENDING"
	SortDirectionType_ASCENDING  SortDirectionType = "ASCENDING"
)

type TaskRunSortColumnType string

const (
	TaskRunSortColumnType_TASK_RUN_TYPE TaskRunSortColumnType = "TASK_RUN_TYPE"
	TaskRunSortColumnType_STATUS        TaskRunSortColumnType = "STATUS"
	TaskRunSortColumnType_STARTED       TaskRunSortColumnType = "STARTED"
)

type TaskStatusType string

const (
	TaskStatusType_STARTING  TaskStatusType = "STARTING"
	TaskStatusType_RUNNING   TaskStatusType = "RUNNING"
	TaskStatusType_STOPPING  TaskStatusType = "STOPPING"
	TaskStatusType_STOPPED   TaskStatusType = "STOPPED"
	TaskStatusType_SUCCEEDED TaskStatusType = "SUCCEEDED"
	TaskStatusType_FAILED    TaskStatusType = "FAILED"
	TaskStatusType_TIMEOUT   TaskStatusType = "TIMEOUT"
)

type TaskType string

const (
	TaskType_EVALUATION              TaskType = "EVALUATION"
	TaskType_LABELING_SET_GENERATION TaskType = "LABELING_SET_GENERATION"
	TaskType_IMPORT_LABELS           TaskType = "IMPORT_LABELS"
	TaskType_EXPORT_LABELS           TaskType = "EXPORT_LABELS"
	TaskType_FIND_MATCHES            TaskType = "FIND_MATCHES"
)

type TransformSortColumnType string

const (
	TransformSortColumnType_NAME           TransformSortColumnType = "NAME"
	TransformSortColumnType_TRANSFORM_TYPE TransformSortColumnType = "TRANSFORM_TYPE"
	TransformSortColumnType_STATUS         TransformSortColumnType = "STATUS"
	TransformSortColumnType_CREATED        TransformSortColumnType = "CREATED"
	TransformSortColumnType_LAST_MODIFIED  TransformSortColumnType = "LAST_MODIFIED"
)

type TransformStatusType string

const (
	TransformStatusType_NOT_READY TransformStatusType = "NOT_READY"
	TransformStatusType_READY     TransformStatusType = "READY"
	TransformStatusType_DELETING  TransformStatusType = "DELETING"
)

type TransformType string

const (
	TransformType_FIND_MATCHES TransformType = "FIND_MATCHES"
)

type TriggerState string

const (
	TriggerState_CREATING     TriggerState = "CREATING"
	TriggerState_CREATED      TriggerState = "CREATED"
	TriggerState_ACTIVATING   TriggerState = "ACTIVATING"
	TriggerState_ACTIVATED    TriggerState = "ACTIVATED"
	TriggerState_DEACTIVATING TriggerState = "DEACTIVATING"
	TriggerState_DEACTIVATED  TriggerState = "DEACTIVATED"
	TriggerState_DELETING     TriggerState = "DELETING"
	TriggerState_UPDATING     TriggerState = "UPDATING"
)

type TriggerType string

const (
	TriggerType_SCHEDULED   TriggerType = "SCHEDULED"
	TriggerType_CONDITIONAL TriggerType = "CONDITIONAL"
	TriggerType_ON_DEMAND   TriggerType = "ON_DEMAND"
	TriggerType_EVENT       TriggerType = "EVENT"
)

type UpdateBehavior string

const (
	UpdateBehavior_LOG                UpdateBehavior = "LOG"
	UpdateBehavior_UPDATE_IN_DATABASE UpdateBehavior = "UPDATE_IN_DATABASE"
)

type WorkerType string

const (
	WorkerType_Standard WorkerType = "Standard"
	WorkerType_G_1X     WorkerType = "G.1X"
	WorkerType_G_2X     WorkerType = "G.2X"
)

type WorkflowRunStatus string

const (
	WorkflowRunStatus_RUNNING   WorkflowRunStatus = "RUNNING"
	WorkflowRunStatus_COMPLETED WorkflowRunStatus = "COMPLETED"
	WorkflowRunStatus_STOPPING  WorkflowRunStatus = "STOPPING"
	WorkflowRunStatus_STOPPED   WorkflowRunStatus = "STOPPED"
	WorkflowRunStatus_ERROR     WorkflowRunStatus = "ERROR"
)
