/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package permission

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/ram"

	svcapitypes "github.com/crossplane-contrib/provider-aws/apis/ram/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateGetPermissionInput returns input for read
// operation.
func GenerateGetPermissionInput(cr *svcapitypes.Permission) *svcsdk.GetPermissionInput {
	res := &svcsdk.GetPermissionInput{}

	return res
}

// GeneratePermission returns the current state in the form of *svcapitypes.Permission.
func GeneratePermission(resp *svcsdk.GetPermissionOutput) *svcapitypes.Permission {
	cr := &svcapitypes.Permission{}

	if resp.Permission.Name != nil {
		cr.Spec.ForProvider.Name = resp.Permission.Name
	} else {
		cr.Spec.ForProvider.Name = nil
	}
	if resp.Permission.Permission != nil {
		f7 := &svcapitypes.ResourceSharePermissionSummary{}
		Permission.f7 = resp.Permission.Permission
		cr.Status.AtProvider.Permission = f7
	} else {
		cr.Status.AtProvider.Permission = nil
	}
	if resp.Permission.ResourceType != nil {
		cr.Spec.ForProvider.ResourceType = resp.Permission.ResourceType
	} else {
		cr.Spec.ForProvider.ResourceType = nil
	}
	if resp.Permission.Tags != nil {
		f11 := []*svcapitypes.Tag{}
		for _, f11iter := range resp.Permission.Tags {
			f11elem := &svcapitypes.Tag{}
			if f11iter.Key != nil {
				f11elem.Key = f11iter.Key
			}
			if f11iter.Value != nil {
				f11elem.Value = f11iter.Value
			}
			f11 = append(f11, f11elem)
		}
		cr.Spec.ForProvider.Tags = f11
	} else {
		cr.Spec.ForProvider.Tags = nil
	}

	return cr
}

// GenerateCreatePermissionInput returns a create input.
func GenerateCreatePermissionInput(cr *svcapitypes.Permission) *svcsdk.CreatePermissionInput {
	res := &svcsdk.CreatePermissionInput{}

	if cr.Spec.ForProvider.ClientToken != nil {
		res.SetClientToken(*cr.Spec.ForProvider.ClientToken)
	}
	if cr.Spec.ForProvider.Name != nil {
		res.SetName(*cr.Spec.ForProvider.Name)
	}
	if cr.Spec.ForProvider.PolicyTemplate != nil {
		res.SetPolicyTemplate(*cr.Spec.ForProvider.PolicyTemplate)
	}
	if cr.Spec.ForProvider.ResourceType != nil {
		res.SetResourceType(*cr.Spec.ForProvider.ResourceType)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f4 := []*svcsdk.Tag{}
		for _, f4iter := range cr.Spec.ForProvider.Tags {
			f4elem := &svcsdk.Tag{}
			if f4iter.Key != nil {
				f4elem.SetKey(*f4iter.Key)
			}
			if f4iter.Value != nil {
				f4elem.SetValue(*f4iter.Value)
			}
			f4 = append(f4, f4elem)
		}
		res.SetTags(f4)
	}

	return res
}

// GenerateDeletePermissionInput returns a deletion input.
func GenerateDeletePermissionInput(cr *svcapitypes.Permission) *svcsdk.DeletePermissionInput {
	res := &svcsdk.DeletePermissionInput{}

	if cr.Spec.ForProvider.ClientToken != nil {
		res.SetClientToken(*cr.Spec.ForProvider.ClientToken)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
