/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package integration

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/apigatewayv2"
	svcsdk "github.com/aws/aws-sdk-go/service/apigatewayv2"
	svcsdkapi "github.com/aws/aws-sdk-go/service/apigatewayv2/apigatewayv2iface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane-contrib/provider-aws/apis/apigatewayv2/v1alpha1"
	connectaws "github.com/crossplane-contrib/provider-aws/pkg/utils/connect/aws"
	errorutils "github.com/crossplane-contrib/provider-aws/pkg/utils/errors"
)

const (
	errUnexpectedObject = "managed resource is not an Integration resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create Integration in AWS"
	errUpdate        = "cannot update Integration in AWS"
	errDescribe      = "failed to describe Integration"
	errDelete        = "failed to delete Integration"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.Integration)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := connectaws.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.Integration)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateGetIntegrationInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.GetIntegrationWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, errorutils.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateIntegration(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)
	upToDate := true
	diff := ""
	if !meta.WasDeleted(cr) { // There is no need to run isUpToDate if the resource is deleted
		upToDate, diff, err = e.isUpToDate(ctx, cr, resp)
		if err != nil {
			return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
		}
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		Diff:                    diff,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.Integration)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateIntegrationInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateIntegrationWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, errorutils.Wrap(err, errCreate)
	}

	if resp.ApiGatewayManaged != nil {
		cr.Status.AtProvider.APIGatewayManaged = resp.ApiGatewayManaged
	} else {
		cr.Status.AtProvider.APIGatewayManaged = nil
	}
	if resp.ConnectionId != nil {
		cr.Spec.ForProvider.ConnectionID = resp.ConnectionId
	} else {
		cr.Spec.ForProvider.ConnectionID = nil
	}
	if resp.ConnectionType != nil {
		cr.Spec.ForProvider.ConnectionType = resp.ConnectionType
	} else {
		cr.Spec.ForProvider.ConnectionType = nil
	}
	if resp.ContentHandlingStrategy != nil {
		cr.Spec.ForProvider.ContentHandlingStrategy = resp.ContentHandlingStrategy
	} else {
		cr.Spec.ForProvider.ContentHandlingStrategy = nil
	}
	if resp.CredentialsArn != nil {
		cr.Spec.ForProvider.CredentialsARN = resp.CredentialsArn
	} else {
		cr.Spec.ForProvider.CredentialsARN = nil
	}
	if resp.Description != nil {
		cr.Spec.ForProvider.Description = resp.Description
	} else {
		cr.Spec.ForProvider.Description = nil
	}
	if resp.IntegrationId != nil {
		cr.Status.AtProvider.IntegrationID = resp.IntegrationId
	} else {
		cr.Status.AtProvider.IntegrationID = nil
	}
	if resp.IntegrationMethod != nil {
		cr.Spec.ForProvider.IntegrationMethod = resp.IntegrationMethod
	} else {
		cr.Spec.ForProvider.IntegrationMethod = nil
	}
	if resp.IntegrationResponseSelectionExpression != nil {
		cr.Status.AtProvider.IntegrationResponseSelectionExpression = resp.IntegrationResponseSelectionExpression
	} else {
		cr.Status.AtProvider.IntegrationResponseSelectionExpression = nil
	}
	if resp.IntegrationSubtype != nil {
		cr.Spec.ForProvider.IntegrationSubtype = resp.IntegrationSubtype
	} else {
		cr.Spec.ForProvider.IntegrationSubtype = nil
	}
	if resp.IntegrationType != nil {
		cr.Spec.ForProvider.IntegrationType = resp.IntegrationType
	} else {
		cr.Spec.ForProvider.IntegrationType = nil
	}
	if resp.IntegrationUri != nil {
		cr.Spec.ForProvider.IntegrationURI = resp.IntegrationUri
	} else {
		cr.Spec.ForProvider.IntegrationURI = nil
	}
	if resp.PassthroughBehavior != nil {
		cr.Spec.ForProvider.PassthroughBehavior = resp.PassthroughBehavior
	} else {
		cr.Spec.ForProvider.PassthroughBehavior = nil
	}
	if resp.PayloadFormatVersion != nil {
		cr.Spec.ForProvider.PayloadFormatVersion = resp.PayloadFormatVersion
	} else {
		cr.Spec.ForProvider.PayloadFormatVersion = nil
	}
	if resp.RequestParameters != nil {
		f14 := map[string]*string{}
		for f14key, f14valiter := range resp.RequestParameters {
			var f14val string
			f14val = *f14valiter
			f14[f14key] = &f14val
		}
		cr.Spec.ForProvider.RequestParameters = f14
	} else {
		cr.Spec.ForProvider.RequestParameters = nil
	}
	if resp.RequestTemplates != nil {
		f15 := map[string]*string{}
		for f15key, f15valiter := range resp.RequestTemplates {
			var f15val string
			f15val = *f15valiter
			f15[f15key] = &f15val
		}
		cr.Spec.ForProvider.RequestTemplates = f15
	} else {
		cr.Spec.ForProvider.RequestTemplates = nil
	}
	if resp.TemplateSelectionExpression != nil {
		cr.Spec.ForProvider.TemplateSelectionExpression = resp.TemplateSelectionExpression
	} else {
		cr.Spec.ForProvider.TemplateSelectionExpression = nil
	}
	if resp.TimeoutInMillis != nil {
		cr.Spec.ForProvider.TimeoutInMillis = resp.TimeoutInMillis
	} else {
		cr.Spec.ForProvider.TimeoutInMillis = nil
	}
	if resp.TlsConfig != nil {
		f18 := &svcapitypes.TLSConfigInput{}
		if resp.TlsConfig.ServerNameToVerify != nil {
			f18.ServerNameToVerify = resp.TlsConfig.ServerNameToVerify
		}
		cr.Spec.ForProvider.TLSConfig = f18
	} else {
		cr.Spec.ForProvider.TLSConfig = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*svcapitypes.Integration)
	if !ok {
		return managed.ExternalUpdate{}, errors.New(errUnexpectedObject)
	}
	input := GenerateUpdateIntegrationInput(cr)
	if err := e.preUpdate(ctx, cr, input); err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, "pre-update failed")
	}
	resp, err := e.client.UpdateIntegrationWithContext(ctx, input)
	return e.postUpdate(ctx, cr, resp, managed.ExternalUpdate{}, errorutils.Wrap(err, errUpdate))
}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.Integration)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeleteIntegrationInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return nil
	}
	resp, err := e.client.DeleteIntegrationWithContext(ctx, input)
	return e.postDelete(ctx, cr, resp, errorutils.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.ApiGatewayV2API, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		preUpdate:      nopPreUpdate,
		postUpdate:     nopPostUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.ApiGatewayV2API
	preObserve     func(context.Context, *svcapitypes.Integration, *svcsdk.GetIntegrationInput) error
	postObserve    func(context.Context, *svcapitypes.Integration, *svcsdk.GetIntegrationOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	lateInitialize func(*svcapitypes.IntegrationParameters, *svcsdk.GetIntegrationOutput) error
	isUpToDate     func(context.Context, *svcapitypes.Integration, *svcsdk.GetIntegrationOutput) (bool, string, error)
	preCreate      func(context.Context, *svcapitypes.Integration, *svcsdk.CreateIntegrationInput) error
	postCreate     func(context.Context, *svcapitypes.Integration, *svcsdk.CreateIntegrationOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete      func(context.Context, *svcapitypes.Integration, *svcsdk.DeleteIntegrationInput) (bool, error)
	postDelete     func(context.Context, *svcapitypes.Integration, *svcsdk.DeleteIntegrationOutput, error) error
	preUpdate      func(context.Context, *svcapitypes.Integration, *svcsdk.UpdateIntegrationInput) error
	postUpdate     func(context.Context, *svcapitypes.Integration, *svcsdk.UpdateIntegrationOutput, managed.ExternalUpdate, error) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.Integration, *svcsdk.GetIntegrationInput) error {
	return nil
}

func nopPostObserve(_ context.Context, _ *svcapitypes.Integration, _ *svcsdk.GetIntegrationOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopLateInitialize(*svcapitypes.IntegrationParameters, *svcsdk.GetIntegrationOutput) error {
	return nil
}
func alwaysUpToDate(context.Context, *svcapitypes.Integration, *svcsdk.GetIntegrationOutput) (bool, string, error) {
	return true, "", nil
}

func nopPreCreate(context.Context, *svcapitypes.Integration, *svcsdk.CreateIntegrationInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.Integration, _ *svcsdk.CreateIntegrationOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.Integration, *svcsdk.DeleteIntegrationInput) (bool, error) {
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.Integration, _ *svcsdk.DeleteIntegrationOutput, err error) error {
	return err
}
func nopPreUpdate(context.Context, *svcapitypes.Integration, *svcsdk.UpdateIntegrationInput) error {
	return nil
}
func nopPostUpdate(_ context.Context, _ *svcapitypes.Integration, _ *svcsdk.UpdateIntegrationOutput, upd managed.ExternalUpdate, err error) (managed.ExternalUpdate, error) {
	return upd, err
}
