/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package accessgrantsinstance

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/s3control"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/crossplane-contrib/provider-aws/apis/s3control/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateGetAccessGrantsInstanceInput returns input for read
// operation.
func GenerateGetAccessGrantsInstanceInput(cr *svcapitypes.AccessGrantsInstance) *svcsdk.GetAccessGrantsInstanceInput {
	res := &svcsdk.GetAccessGrantsInstanceInput{}

	if cr.Spec.ForProvider.AccountID != nil {
		res.SetAccountId(*cr.Spec.ForProvider.AccountID)
	}

	return res
}

// GenerateAccessGrantsInstance returns the current state in the form of *svcapitypes.AccessGrantsInstance.
func GenerateAccessGrantsInstance(resp *svcsdk.GetAccessGrantsInstanceOutput) *svcapitypes.AccessGrantsInstance {
	cr := &svcapitypes.AccessGrantsInstance{}

	if resp.AccessGrantsInstanceArn != nil {
		cr.Status.AtProvider.AccessGrantsInstanceARN = resp.AccessGrantsInstanceArn
	} else {
		cr.Status.AtProvider.AccessGrantsInstanceARN = nil
	}
	if resp.AccessGrantsInstanceId != nil {
		cr.Status.AtProvider.AccessGrantsInstanceID = resp.AccessGrantsInstanceId
	} else {
		cr.Status.AtProvider.AccessGrantsInstanceID = nil
	}
	if resp.CreatedAt != nil {
		cr.Status.AtProvider.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		cr.Status.AtProvider.CreatedAt = nil
	}
	if resp.IdentityCenterArn != nil {
		cr.Spec.ForProvider.IdentityCenterARN = resp.IdentityCenterArn
	} else {
		cr.Spec.ForProvider.IdentityCenterARN = nil
	}

	return cr
}

// GenerateCreateAccessGrantsInstanceInput returns a create input.
func GenerateCreateAccessGrantsInstanceInput(cr *svcapitypes.AccessGrantsInstance) *svcsdk.CreateAccessGrantsInstanceInput {
	res := &svcsdk.CreateAccessGrantsInstanceInput{}

	if cr.Spec.ForProvider.AccountID != nil {
		res.SetAccountId(*cr.Spec.ForProvider.AccountID)
	}
	if cr.Spec.ForProvider.IdentityCenterARN != nil {
		res.SetIdentityCenterArn(*cr.Spec.ForProvider.IdentityCenterARN)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f2 := []*svcsdk.Tag{}
		for _, f2iter := range cr.Spec.ForProvider.Tags {
			f2elem := &svcsdk.Tag{}
			if f2iter.Key != nil {
				f2elem.SetKey(*f2iter.Key)
			}
			if f2iter.Value != nil {
				f2elem.SetValue(*f2iter.Value)
			}
			f2 = append(f2, f2elem)
		}
		res.SetTags(f2)
	}

	return res
}

// GenerateDeleteAccessGrantsInstanceInput returns a deletion input.
func GenerateDeleteAccessGrantsInstanceInput(cr *svcapitypes.AccessGrantsInstance) *svcsdk.DeleteAccessGrantsInstanceInput {
	res := &svcsdk.DeleteAccessGrantsInstanceInput{}

	if cr.Spec.ForProvider.AccountID != nil {
		res.SetAccountId(*cr.Spec.ForProvider.AccountID)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
