/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package volume

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/ec2"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	svcsdkapi "github.com/aws/aws-sdk-go/service/ec2/ec2iface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane-contrib/provider-aws/apis/ec2/v1alpha1"
	connectaws "github.com/crossplane-contrib/provider-aws/pkg/utils/connect/aws"
	errorutils "github.com/crossplane-contrib/provider-aws/pkg/utils/errors"
)

const (
	errUnexpectedObject = "managed resource is not an Volume resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create Volume in AWS"
	errUpdate        = "cannot update Volume in AWS"
	errDescribe      = "failed to describe Volume"
	errDelete        = "failed to delete Volume"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.Volume)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := connectaws.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.Volume)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateDescribeVolumesInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.DescribeVolumesWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, errorutils.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	resp = e.filterList(cr, resp)
	if len(resp.Volumes) == 0 {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateVolume(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)
	upToDate := true
	diff := ""
	if !meta.WasDeleted(cr) { // There is no need to run isUpToDate if the resource is deleted
		upToDate, diff, err = e.isUpToDate(ctx, cr, resp)
		if err != nil {
			return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
		}
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		Diff:                    diff,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.Volume)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateVolumeInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateVolumeWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, errorutils.Wrap(err, errCreate)
	}

	if resp.Attachments != nil {
		f0 := []*svcapitypes.VolumeAttachment{}
		for _, f0iter := range resp.Attachments {
			f0elem := &svcapitypes.VolumeAttachment{}
			if f0iter.AttachTime != nil {
				f0elem.AttachTime = &metav1.Time{*f0iter.AttachTime}
			}
			if f0iter.DeleteOnTermination != nil {
				f0elem.DeleteOnTermination = f0iter.DeleteOnTermination
			}
			if f0iter.Device != nil {
				f0elem.Device = f0iter.Device
			}
			if f0iter.InstanceId != nil {
				f0elem.InstanceID = f0iter.InstanceId
			}
			if f0iter.State != nil {
				f0elem.State = f0iter.State
			}
			if f0iter.VolumeId != nil {
				f0elem.VolumeID = f0iter.VolumeId
			}
			f0 = append(f0, f0elem)
		}
		cr.Status.AtProvider.Attachments = f0
	} else {
		cr.Status.AtProvider.Attachments = nil
	}
	if resp.AvailabilityZone != nil {
		cr.Spec.ForProvider.AvailabilityZone = resp.AvailabilityZone
	} else {
		cr.Spec.ForProvider.AvailabilityZone = nil
	}
	if resp.CreateTime != nil {
		cr.Status.AtProvider.CreateTime = &metav1.Time{*resp.CreateTime}
	} else {
		cr.Status.AtProvider.CreateTime = nil
	}
	if resp.Encrypted != nil {
		cr.Spec.ForProvider.Encrypted = resp.Encrypted
	} else {
		cr.Spec.ForProvider.Encrypted = nil
	}
	if resp.FastRestored != nil {
		cr.Status.AtProvider.FastRestored = resp.FastRestored
	} else {
		cr.Status.AtProvider.FastRestored = nil
	}
	if resp.Iops != nil {
		cr.Spec.ForProvider.IOPS = resp.Iops
	} else {
		cr.Spec.ForProvider.IOPS = nil
	}
	if resp.KmsKeyId != nil {
		cr.Status.AtProvider.KMSKeyID = resp.KmsKeyId
	} else {
		cr.Status.AtProvider.KMSKeyID = nil
	}
	if resp.MultiAttachEnabled != nil {
		cr.Spec.ForProvider.MultiAttachEnabled = resp.MultiAttachEnabled
	} else {
		cr.Spec.ForProvider.MultiAttachEnabled = nil
	}
	if resp.OutpostArn != nil {
		cr.Spec.ForProvider.OutpostARN = resp.OutpostArn
	} else {
		cr.Spec.ForProvider.OutpostARN = nil
	}
	if resp.Size != nil {
		cr.Spec.ForProvider.Size = resp.Size
	} else {
		cr.Spec.ForProvider.Size = nil
	}
	if resp.SnapshotId != nil {
		cr.Spec.ForProvider.SnapshotID = resp.SnapshotId
	} else {
		cr.Spec.ForProvider.SnapshotID = nil
	}
	if resp.SseType != nil {
		cr.Status.AtProvider.SSEType = resp.SseType
	} else {
		cr.Status.AtProvider.SSEType = nil
	}
	if resp.State != nil {
		cr.Status.AtProvider.State = resp.State
	} else {
		cr.Status.AtProvider.State = nil
	}
	if resp.Tags != nil {
		f13 := []*svcapitypes.Tag{}
		for _, f13iter := range resp.Tags {
			f13elem := &svcapitypes.Tag{}
			if f13iter.Key != nil {
				f13elem.Key = f13iter.Key
			}
			if f13iter.Value != nil {
				f13elem.Value = f13iter.Value
			}
			f13 = append(f13, f13elem)
		}
		cr.Status.AtProvider.Tags = f13
	} else {
		cr.Status.AtProvider.Tags = nil
	}
	if resp.Throughput != nil {
		cr.Spec.ForProvider.Throughput = resp.Throughput
	} else {
		cr.Spec.ForProvider.Throughput = nil
	}
	if resp.VolumeId != nil {
		cr.Status.AtProvider.VolumeID = resp.VolumeId
	} else {
		cr.Status.AtProvider.VolumeID = nil
	}
	if resp.VolumeType != nil {
		cr.Spec.ForProvider.VolumeType = resp.VolumeType
	} else {
		cr.Spec.ForProvider.VolumeType = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*svcapitypes.Volume)
	if !ok {
		return managed.ExternalUpdate{}, errors.New(errUnexpectedObject)
	}
	input := GenerateModifyVolumeInput(cr)
	if err := e.preUpdate(ctx, cr, input); err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, "pre-update failed")
	}
	resp, err := e.client.ModifyVolumeWithContext(ctx, input)
	return e.postUpdate(ctx, cr, resp, managed.ExternalUpdate{}, errorutils.Wrap(err, errUpdate))
}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.Volume)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeleteVolumeInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return nil
	}
	resp, err := e.client.DeleteVolumeWithContext(ctx, input)
	return e.postDelete(ctx, cr, resp, errorutils.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.EC2API, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		filterList:     nopFilterList,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		preUpdate:      nopPreUpdate,
		postUpdate:     nopPostUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.EC2API
	preObserve     func(context.Context, *svcapitypes.Volume, *svcsdk.DescribeVolumesInput) error
	postObserve    func(context.Context, *svcapitypes.Volume, *svcsdk.DescribeVolumesOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	filterList     func(*svcapitypes.Volume, *svcsdk.DescribeVolumesOutput) *svcsdk.DescribeVolumesOutput
	lateInitialize func(*svcapitypes.VolumeParameters, *svcsdk.DescribeVolumesOutput) error
	isUpToDate     func(context.Context, *svcapitypes.Volume, *svcsdk.DescribeVolumesOutput) (bool, string, error)
	preCreate      func(context.Context, *svcapitypes.Volume, *svcsdk.CreateVolumeInput) error
	postCreate     func(context.Context, *svcapitypes.Volume, *svcsdk.Volume, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete      func(context.Context, *svcapitypes.Volume, *svcsdk.DeleteVolumeInput) (bool, error)
	postDelete     func(context.Context, *svcapitypes.Volume, *svcsdk.DeleteVolumeOutput, error) error
	preUpdate      func(context.Context, *svcapitypes.Volume, *svcsdk.ModifyVolumeInput) error
	postUpdate     func(context.Context, *svcapitypes.Volume, *svcsdk.ModifyVolumeOutput, managed.ExternalUpdate, error) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.Volume, *svcsdk.DescribeVolumesInput) error {
	return nil
}
func nopPostObserve(_ context.Context, _ *svcapitypes.Volume, _ *svcsdk.DescribeVolumesOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopFilterList(_ *svcapitypes.Volume, list *svcsdk.DescribeVolumesOutput) *svcsdk.DescribeVolumesOutput {
	return list
}

func nopLateInitialize(*svcapitypes.VolumeParameters, *svcsdk.DescribeVolumesOutput) error {
	return nil
}
func alwaysUpToDate(context.Context, *svcapitypes.Volume, *svcsdk.DescribeVolumesOutput) (bool, string, error) {
	return true, "", nil
}

func nopPreCreate(context.Context, *svcapitypes.Volume, *svcsdk.CreateVolumeInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.Volume, _ *svcsdk.Volume, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.Volume, *svcsdk.DeleteVolumeInput) (bool, error) {
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.Volume, _ *svcsdk.DeleteVolumeOutput, err error) error {
	return err
}
func nopPreUpdate(context.Context, *svcapitypes.Volume, *svcsdk.ModifyVolumeInput) error {
	return nil
}
func nopPostUpdate(_ context.Context, _ *svcapitypes.Volume, _ *svcsdk.ModifyVolumeOutput, upd managed.ExternalUpdate, err error) (managed.ExternalUpdate, error) {
	return upd, err
}
