//go:build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorCountRequest) DeepCopyInto(out *AcceleratorCountRequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorCountRequest.
func (in *AcceleratorCountRequest) DeepCopy() *AcceleratorCountRequest {
	if in == nil {
		return nil
	}
	out := new(AcceleratorCountRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorTotalMemoryMiBRequest) DeepCopyInto(out *AcceleratorTotalMemoryMiBRequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorTotalMemoryMiBRequest.
func (in *AcceleratorTotalMemoryMiBRequest) DeepCopy() *AcceleratorTotalMemoryMiBRequest {
	if in == nil {
		return nil
	}
	out := new(AcceleratorTotalMemoryMiBRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Activity) DeepCopyInto(out *Activity) {
	*out = *in
	if in.ActivityID != nil {
		in, out := &in.ActivityID, &out.ActivityID
		*out = new(string)
		**out = **in
	}
	if in.AutoScalingGroupARN != nil {
		in, out := &in.AutoScalingGroupARN, &out.AutoScalingGroupARN
		*out = new(string)
		**out = **in
	}
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.Cause != nil {
		in, out := &in.Cause, &out.Cause
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Activity.
func (in *Activity) DeepCopy() *Activity {
	if in == nil {
		return nil
	}
	out := new(Activity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdjustmentType) DeepCopyInto(out *AdjustmentType) {
	*out = *in
	if in.AdjustmentType != nil {
		in, out := &in.AdjustmentType, &out.AdjustmentType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdjustmentType.
func (in *AdjustmentType) DeepCopy() *AdjustmentType {
	if in == nil {
		return nil
	}
	out := new(AdjustmentType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alarm) DeepCopyInto(out *Alarm) {
	*out = *in
	if in.AlarmARN != nil {
		in, out := &in.AlarmARN, &out.AlarmARN
		*out = new(string)
		**out = **in
	}
	if in.AlarmName != nil {
		in, out := &in.AlarmName, &out.AlarmName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alarm.
func (in *Alarm) DeepCopy() *Alarm {
	if in == nil {
		return nil
	}
	out := new(Alarm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingGroup) DeepCopyInto(out *AutoScalingGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingGroup.
func (in *AutoScalingGroup) DeepCopy() *AutoScalingGroup {
	if in == nil {
		return nil
	}
	out := new(AutoScalingGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoScalingGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingGroupList) DeepCopyInto(out *AutoScalingGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoScalingGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingGroupList.
func (in *AutoScalingGroupList) DeepCopy() *AutoScalingGroupList {
	if in == nil {
		return nil
	}
	out := new(AutoScalingGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoScalingGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingGroupObservation) DeepCopyInto(out *AutoScalingGroupObservation) {
	*out = *in
	if in.AutoScalingGroupARN != nil {
		in, out := &in.AutoScalingGroupARN, &out.AutoScalingGroupARN
		*out = new(string)
		**out = **in
	}
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CapacityRebalance != nil {
		in, out := &in.CapacityRebalance, &out.CapacityRebalance
		*out = new(bool)
		**out = **in
	}
	if in.DefaultCooldown != nil {
		in, out := &in.DefaultCooldown, &out.DefaultCooldown
		*out = new(int64)
		**out = **in
	}
	if in.DefaultInstanceWarmup != nil {
		in, out := &in.DefaultInstanceWarmup, &out.DefaultInstanceWarmup
		*out = new(int64)
		**out = **in
	}
	if in.DesiredCapacity != nil {
		in, out := &in.DesiredCapacity, &out.DesiredCapacity
		*out = new(int64)
		**out = **in
	}
	if in.DesiredCapacityType != nil {
		in, out := &in.DesiredCapacityType, &out.DesiredCapacityType
		*out = (*in).DeepCopy()
	}
	if in.EnabledMetrics != nil {
		in, out := &in.EnabledMetrics, &out.EnabledMetrics
		*out = make([]*EnabledMetric, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(EnabledMetric)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.HealthCheckGracePeriod != nil {
		in, out := &in.HealthCheckGracePeriod, &out.HealthCheckGracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.HealthCheckType != nil {
		in, out := &in.HealthCheckType, &out.HealthCheckType
		*out = new(string)
		**out = **in
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]*Instance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Instance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.LaunchConfigurationName != nil {
		in, out := &in.LaunchConfigurationName, &out.LaunchConfigurationName
		*out = new(string)
		**out = **in
	}
	if in.LaunchTemplate != nil {
		in, out := &in.LaunchTemplate, &out.LaunchTemplate
		*out = new(LaunchTemplateSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerNames != nil {
		in, out := &in.LoadBalancerNames, &out.LoadBalancerNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxInstanceLifetime != nil {
		in, out := &in.MaxInstanceLifetime, &out.MaxInstanceLifetime
		*out = new(int64)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int64)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(int64)
		**out = **in
	}
	if in.MixedInstancesPolicy != nil {
		in, out := &in.MixedInstancesPolicy, &out.MixedInstancesPolicy
		*out = new(MixedInstancesPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.NewInstancesProtectedFromScaleIn != nil {
		in, out := &in.NewInstancesProtectedFromScaleIn, &out.NewInstancesProtectedFromScaleIn
		*out = new(bool)
		**out = **in
	}
	if in.PlacementGroup != nil {
		in, out := &in.PlacementGroup, &out.PlacementGroup
		*out = new(string)
		**out = **in
	}
	if in.PredictedCapacity != nil {
		in, out := &in.PredictedCapacity, &out.PredictedCapacity
		*out = new(int64)
		**out = **in
	}
	if in.ServiceLinkedRoleARN != nil {
		in, out := &in.ServiceLinkedRoleARN, &out.ServiceLinkedRoleARN
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SuspendedProcesses != nil {
		in, out := &in.SuspendedProcesses, &out.SuspendedProcesses
		*out = make([]*SuspendedProcess, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SuspendedProcess)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*TagDescription, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TagDescription)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TargetGroupARNs != nil {
		in, out := &in.TargetGroupARNs, &out.TargetGroupARNs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TerminationPolicies != nil {
		in, out := &in.TerminationPolicies, &out.TerminationPolicies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TrafficSources != nil {
		in, out := &in.TrafficSources, &out.TrafficSources
		*out = make([]*TrafficSourceIdentifier, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TrafficSourceIdentifier)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.VPCZoneIdentifier != nil {
		in, out := &in.VPCZoneIdentifier, &out.VPCZoneIdentifier
		*out = new(string)
		**out = **in
	}
	if in.WarmPoolConfiguration != nil {
		in, out := &in.WarmPoolConfiguration, &out.WarmPoolConfiguration
		*out = new(WarmPoolConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WarmPoolSize != nil {
		in, out := &in.WarmPoolSize, &out.WarmPoolSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingGroupObservation.
func (in *AutoScalingGroupObservation) DeepCopy() *AutoScalingGroupObservation {
	if in == nil {
		return nil
	}
	out := new(AutoScalingGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingGroupParameters) DeepCopyInto(out *AutoScalingGroupParameters) {
	*out = *in
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CapacityRebalance != nil {
		in, out := &in.CapacityRebalance, &out.CapacityRebalance
		*out = new(bool)
		**out = **in
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(string)
		**out = **in
	}
	if in.DefaultCooldown != nil {
		in, out := &in.DefaultCooldown, &out.DefaultCooldown
		*out = new(int64)
		**out = **in
	}
	if in.DefaultInstanceWarmup != nil {
		in, out := &in.DefaultInstanceWarmup, &out.DefaultInstanceWarmup
		*out = new(int64)
		**out = **in
	}
	if in.DesiredCapacity != nil {
		in, out := &in.DesiredCapacity, &out.DesiredCapacity
		*out = new(int64)
		**out = **in
	}
	if in.DesiredCapacityType != nil {
		in, out := &in.DesiredCapacityType, &out.DesiredCapacityType
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckGracePeriod != nil {
		in, out := &in.HealthCheckGracePeriod, &out.HealthCheckGracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.HealthCheckType != nil {
		in, out := &in.HealthCheckType, &out.HealthCheckType
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.LaunchConfigurationName != nil {
		in, out := &in.LaunchConfigurationName, &out.LaunchConfigurationName
		*out = new(string)
		**out = **in
	}
	if in.LaunchTemplate != nil {
		in, out := &in.LaunchTemplate, &out.LaunchTemplate
		*out = new(LaunchTemplateSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.LifecycleHookSpecificationList != nil {
		in, out := &in.LifecycleHookSpecificationList, &out.LifecycleHookSpecificationList
		*out = make([]*LifecycleHookSpecification, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(LifecycleHookSpecification)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.LoadBalancerNames != nil {
		in, out := &in.LoadBalancerNames, &out.LoadBalancerNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxInstanceLifetime != nil {
		in, out := &in.MaxInstanceLifetime, &out.MaxInstanceLifetime
		*out = new(int64)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int64)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(int64)
		**out = **in
	}
	if in.MixedInstancesPolicy != nil {
		in, out := &in.MixedInstancesPolicy, &out.MixedInstancesPolicy
		*out = new(MixedInstancesPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.NewInstancesProtectedFromScaleIn != nil {
		in, out := &in.NewInstancesProtectedFromScaleIn, &out.NewInstancesProtectedFromScaleIn
		*out = new(bool)
		**out = **in
	}
	if in.PlacementGroup != nil {
		in, out := &in.PlacementGroup, &out.PlacementGroup
		*out = new(string)
		**out = **in
	}
	if in.ServiceLinkedRoleARN != nil {
		in, out := &in.ServiceLinkedRoleARN, &out.ServiceLinkedRoleARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TargetGroupARNs != nil {
		in, out := &in.TargetGroupARNs, &out.TargetGroupARNs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TerminationPolicies != nil {
		in, out := &in.TerminationPolicies, &out.TerminationPolicies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VPCZoneIdentifier != nil {
		in, out := &in.VPCZoneIdentifier, &out.VPCZoneIdentifier
		*out = new(string)
		**out = **in
	}
	out.CustomAutoScalingGroupParameters = in.CustomAutoScalingGroupParameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingGroupParameters.
func (in *AutoScalingGroupParameters) DeepCopy() *AutoScalingGroupParameters {
	if in == nil {
		return nil
	}
	out := new(AutoScalingGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingGroupSpec) DeepCopyInto(out *AutoScalingGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingGroupSpec.
func (in *AutoScalingGroupSpec) DeepCopy() *AutoScalingGroupSpec {
	if in == nil {
		return nil
	}
	out := new(AutoScalingGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingGroupStatus) DeepCopyInto(out *AutoScalingGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingGroupStatus.
func (in *AutoScalingGroupStatus) DeepCopy() *AutoScalingGroupStatus {
	if in == nil {
		return nil
	}
	out := new(AutoScalingGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselineEBSBandwidthMbpsRequest) DeepCopyInto(out *BaselineEBSBandwidthMbpsRequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselineEBSBandwidthMbpsRequest.
func (in *BaselineEBSBandwidthMbpsRequest) DeepCopy() *BaselineEBSBandwidthMbpsRequest {
	if in == nil {
		return nil
	}
	out := new(BaselineEBSBandwidthMbpsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDeviceMapping) DeepCopyInto(out *BlockDeviceMapping) {
	*out = *in
	if in.DeviceName != nil {
		in, out := &in.DeviceName, &out.DeviceName
		*out = new(string)
		**out = **in
	}
	if in.VirtualName != nil {
		in, out := &in.VirtualName, &out.VirtualName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDeviceMapping.
func (in *BlockDeviceMapping) DeepCopy() *BlockDeviceMapping {
	if in == nil {
		return nil
	}
	out := new(BlockDeviceMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAutoScalingGroupParameters) DeepCopyInto(out *CustomAutoScalingGroupParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAutoScalingGroupParameters.
func (in *CustomAutoScalingGroupParameters) DeepCopy() *CustomAutoScalingGroupParameters {
	if in == nil {
		return nil
	}
	out := new(CustomAutoScalingGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesiredConfiguration) DeepCopyInto(out *DesiredConfiguration) {
	*out = *in
	if in.LaunchTemplate != nil {
		in, out := &in.LaunchTemplate, &out.LaunchTemplate
		*out = new(LaunchTemplateSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.MixedInstancesPolicy != nil {
		in, out := &in.MixedInstancesPolicy, &out.MixedInstancesPolicy
		*out = new(MixedInstancesPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesiredConfiguration.
func (in *DesiredConfiguration) DeepCopy() *DesiredConfiguration {
	if in == nil {
		return nil
	}
	out := new(DesiredConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBS) DeepCopyInto(out *EBS) {
	*out = *in
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBS.
func (in *EBS) DeepCopy() *EBS {
	if in == nil {
		return nil
	}
	out := new(EBS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnabledMetric) DeepCopyInto(out *EnabledMetric) {
	*out = *in
	if in.Granularity != nil {
		in, out := &in.Granularity, &out.Granularity
		*out = new(string)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnabledMetric.
func (in *EnabledMetric) DeepCopy() *EnabledMetric {
	if in == nil {
		return nil
	}
	out := new(EnabledMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedScheduledUpdateGroupActionRequest) DeepCopyInto(out *FailedScheduledUpdateGroupActionRequest) {
	*out = *in
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
	if in.ScheduledActionName != nil {
		in, out := &in.ScheduledActionName, &out.ScheduledActionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedScheduledUpdateGroupActionRequest.
func (in *FailedScheduledUpdateGroupActionRequest) DeepCopy() *FailedScheduledUpdateGroupActionRequest {
	if in == nil {
		return nil
	}
	out := new(FailedScheduledUpdateGroupActionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	if in.AutoScalingGroupARN != nil {
		in, out := &in.AutoScalingGroupARN, &out.AutoScalingGroupARN
		*out = new(string)
		**out = **in
	}
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CapacityRebalance != nil {
		in, out := &in.CapacityRebalance, &out.CapacityRebalance
		*out = new(bool)
		**out = **in
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(string)
		**out = **in
	}
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.DefaultCooldown != nil {
		in, out := &in.DefaultCooldown, &out.DefaultCooldown
		*out = new(int64)
		**out = **in
	}
	if in.DefaultInstanceWarmup != nil {
		in, out := &in.DefaultInstanceWarmup, &out.DefaultInstanceWarmup
		*out = new(int64)
		**out = **in
	}
	if in.DesiredCapacity != nil {
		in, out := &in.DesiredCapacity, &out.DesiredCapacity
		*out = new(int64)
		**out = **in
	}
	if in.DesiredCapacityType != nil {
		in, out := &in.DesiredCapacityType, &out.DesiredCapacityType
		*out = new(string)
		**out = **in
	}
	if in.EnabledMetrics != nil {
		in, out := &in.EnabledMetrics, &out.EnabledMetrics
		*out = make([]*EnabledMetric, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(EnabledMetric)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.HealthCheckGracePeriod != nil {
		in, out := &in.HealthCheckGracePeriod, &out.HealthCheckGracePeriod
		*out = new(int64)
		**out = **in
	}
	if in.HealthCheckType != nil {
		in, out := &in.HealthCheckType, &out.HealthCheckType
		*out = new(string)
		**out = **in
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]*Instance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Instance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.LaunchConfigurationName != nil {
		in, out := &in.LaunchConfigurationName, &out.LaunchConfigurationName
		*out = new(string)
		**out = **in
	}
	if in.LaunchTemplate != nil {
		in, out := &in.LaunchTemplate, &out.LaunchTemplate
		*out = new(LaunchTemplateSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerNames != nil {
		in, out := &in.LoadBalancerNames, &out.LoadBalancerNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxInstanceLifetime != nil {
		in, out := &in.MaxInstanceLifetime, &out.MaxInstanceLifetime
		*out = new(int64)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int64)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(int64)
		**out = **in
	}
	if in.MixedInstancesPolicy != nil {
		in, out := &in.MixedInstancesPolicy, &out.MixedInstancesPolicy
		*out = new(MixedInstancesPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.NewInstancesProtectedFromScaleIn != nil {
		in, out := &in.NewInstancesProtectedFromScaleIn, &out.NewInstancesProtectedFromScaleIn
		*out = new(bool)
		**out = **in
	}
	if in.PlacementGroup != nil {
		in, out := &in.PlacementGroup, &out.PlacementGroup
		*out = new(string)
		**out = **in
	}
	if in.PredictedCapacity != nil {
		in, out := &in.PredictedCapacity, &out.PredictedCapacity
		*out = new(int64)
		**out = **in
	}
	if in.ServiceLinkedRoleARN != nil {
		in, out := &in.ServiceLinkedRoleARN, &out.ServiceLinkedRoleARN
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SuspendedProcesses != nil {
		in, out := &in.SuspendedProcesses, &out.SuspendedProcesses
		*out = make([]*SuspendedProcess, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SuspendedProcess)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*TagDescription, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TagDescription)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TargetGroupARNs != nil {
		in, out := &in.TargetGroupARNs, &out.TargetGroupARNs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TerminationPolicies != nil {
		in, out := &in.TerminationPolicies, &out.TerminationPolicies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TrafficSources != nil {
		in, out := &in.TrafficSources, &out.TrafficSources
		*out = make([]*TrafficSourceIdentifier, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TrafficSourceIdentifier)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.VPCZoneIdentifier != nil {
		in, out := &in.VPCZoneIdentifier, &out.VPCZoneIdentifier
		*out = new(string)
		**out = **in
	}
	if in.WarmPoolConfiguration != nil {
		in, out := &in.WarmPoolConfiguration, &out.WarmPoolConfiguration
		*out = new(WarmPoolConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WarmPoolSize != nil {
		in, out := &in.WarmPoolSize, &out.WarmPoolSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	if in.AvailabilityZone != nil {
		in, out := &in.AvailabilityZone, &out.AvailabilityZone
		*out = new(string)
		**out = **in
	}
	if in.HealthStatus != nil {
		in, out := &in.HealthStatus, &out.HealthStatus
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.InstanceType != nil {
		in, out := &in.InstanceType, &out.InstanceType
		*out = new(string)
		**out = **in
	}
	if in.LaunchConfigurationName != nil {
		in, out := &in.LaunchConfigurationName, &out.LaunchConfigurationName
		*out = new(string)
		**out = **in
	}
	if in.LaunchTemplate != nil {
		in, out := &in.LaunchTemplate, &out.LaunchTemplate
		*out = new(LaunchTemplateSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.LifecycleState != nil {
		in, out := &in.LifecycleState, &out.LifecycleState
		*out = new(string)
		**out = **in
	}
	if in.ProtectedFromScaleIn != nil {
		in, out := &in.ProtectedFromScaleIn, &out.ProtectedFromScaleIn
		*out = new(bool)
		**out = **in
	}
	if in.WeightedCapacity != nil {
		in, out := &in.WeightedCapacity, &out.WeightedCapacity
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceDetails) DeepCopyInto(out *InstanceDetails) {
	*out = *in
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZone != nil {
		in, out := &in.AvailabilityZone, &out.AvailabilityZone
		*out = new(string)
		**out = **in
	}
	if in.HealthStatus != nil {
		in, out := &in.HealthStatus, &out.HealthStatus
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.InstanceType != nil {
		in, out := &in.InstanceType, &out.InstanceType
		*out = new(string)
		**out = **in
	}
	if in.LaunchConfigurationName != nil {
		in, out := &in.LaunchConfigurationName, &out.LaunchConfigurationName
		*out = new(string)
		**out = **in
	}
	if in.LaunchTemplate != nil {
		in, out := &in.LaunchTemplate, &out.LaunchTemplate
		*out = new(LaunchTemplateSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.LifecycleState != nil {
		in, out := &in.LifecycleState, &out.LifecycleState
		*out = new(string)
		**out = **in
	}
	if in.ProtectedFromScaleIn != nil {
		in, out := &in.ProtectedFromScaleIn, &out.ProtectedFromScaleIn
		*out = new(bool)
		**out = **in
	}
	if in.WeightedCapacity != nil {
		in, out := &in.WeightedCapacity, &out.WeightedCapacity
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceDetails.
func (in *InstanceDetails) DeepCopy() *InstanceDetails {
	if in == nil {
		return nil
	}
	out := new(InstanceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRefresh) DeepCopyInto(out *InstanceRefresh) {
	*out = *in
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.InstanceRefreshID != nil {
		in, out := &in.InstanceRefreshID, &out.InstanceRefreshID
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.StatusReason != nil {
		in, out := &in.StatusReason, &out.StatusReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRefresh.
func (in *InstanceRefresh) DeepCopy() *InstanceRefresh {
	if in == nil {
		return nil
	}
	out := new(InstanceRefresh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRequirements) DeepCopyInto(out *InstanceRequirements) {
	*out = *in
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(AcceleratorCountRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.AcceleratorManufacturers != nil {
		in, out := &in.AcceleratorManufacturers, &out.AcceleratorManufacturers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AcceleratorNames != nil {
		in, out := &in.AcceleratorNames, &out.AcceleratorNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AcceleratorTotalMemoryMiB != nil {
		in, out := &in.AcceleratorTotalMemoryMiB, &out.AcceleratorTotalMemoryMiB
		*out = new(AcceleratorTotalMemoryMiBRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.AcceleratorTypes != nil {
		in, out := &in.AcceleratorTypes, &out.AcceleratorTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedInstanceTypes != nil {
		in, out := &in.AllowedInstanceTypes, &out.AllowedInstanceTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BareMetal != nil {
		in, out := &in.BareMetal, &out.BareMetal
		*out = new(string)
		**out = **in
	}
	if in.BaselineEBSBandwidthMbps != nil {
		in, out := &in.BaselineEBSBandwidthMbps, &out.BaselineEBSBandwidthMbps
		*out = new(BaselineEBSBandwidthMbpsRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.BurstablePerformance != nil {
		in, out := &in.BurstablePerformance, &out.BurstablePerformance
		*out = new(string)
		**out = **in
	}
	if in.CPUManufacturers != nil {
		in, out := &in.CPUManufacturers, &out.CPUManufacturers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExcludedInstanceTypes != nil {
		in, out := &in.ExcludedInstanceTypes, &out.ExcludedInstanceTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.InstanceGenerations != nil {
		in, out := &in.InstanceGenerations, &out.InstanceGenerations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LocalStorage != nil {
		in, out := &in.LocalStorage, &out.LocalStorage
		*out = new(string)
		**out = **in
	}
	if in.LocalStorageTypes != nil {
		in, out := &in.LocalStorageTypes, &out.LocalStorageTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MemoryGiBPerVCPU != nil {
		in, out := &in.MemoryGiBPerVCPU, &out.MemoryGiBPerVCPU
		*out = new(MemoryGiBPerVCPURequest)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryMiB != nil {
		in, out := &in.MemoryMiB, &out.MemoryMiB
		*out = new(MemoryMiBRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkBandwidthGbps != nil {
		in, out := &in.NetworkBandwidthGbps, &out.NetworkBandwidthGbps
		*out = new(NetworkBandwidthGbpsRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkInterfaceCount != nil {
		in, out := &in.NetworkInterfaceCount, &out.NetworkInterfaceCount
		*out = new(NetworkInterfaceCountRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.OnDemandMaxPricePercentageOverLowestPrice != nil {
		in, out := &in.OnDemandMaxPricePercentageOverLowestPrice, &out.OnDemandMaxPricePercentageOverLowestPrice
		*out = new(int64)
		**out = **in
	}
	if in.RequireHibernateSupport != nil {
		in, out := &in.RequireHibernateSupport, &out.RequireHibernateSupport
		*out = new(bool)
		**out = **in
	}
	if in.SpotMaxPricePercentageOverLowestPrice != nil {
		in, out := &in.SpotMaxPricePercentageOverLowestPrice, &out.SpotMaxPricePercentageOverLowestPrice
		*out = new(int64)
		**out = **in
	}
	if in.TotalLocalStorageGB != nil {
		in, out := &in.TotalLocalStorageGB, &out.TotalLocalStorageGB
		*out = new(TotalLocalStorageGBRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.VCPUCount != nil {
		in, out := &in.VCPUCount, &out.VCPUCount
		*out = new(VCPUCountRequest)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRequirements.
func (in *InstanceRequirements) DeepCopy() *InstanceRequirements {
	if in == nil {
		return nil
	}
	out := new(InstanceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceReusePolicy) DeepCopyInto(out *InstanceReusePolicy) {
	*out = *in
	if in.ReuseOnScaleIn != nil {
		in, out := &in.ReuseOnScaleIn, &out.ReuseOnScaleIn
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceReusePolicy.
func (in *InstanceReusePolicy) DeepCopy() *InstanceReusePolicy {
	if in == nil {
		return nil
	}
	out := new(InstanceReusePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancesDistribution) DeepCopyInto(out *InstancesDistribution) {
	*out = *in
	if in.OnDemandAllocationStrategy != nil {
		in, out := &in.OnDemandAllocationStrategy, &out.OnDemandAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.OnDemandBaseCapacity != nil {
		in, out := &in.OnDemandBaseCapacity, &out.OnDemandBaseCapacity
		*out = new(int64)
		**out = **in
	}
	if in.OnDemandPercentageAboveBaseCapacity != nil {
		in, out := &in.OnDemandPercentageAboveBaseCapacity, &out.OnDemandPercentageAboveBaseCapacity
		*out = new(int64)
		**out = **in
	}
	if in.SpotAllocationStrategy != nil {
		in, out := &in.SpotAllocationStrategy, &out.SpotAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.SpotInstancePools != nil {
		in, out := &in.SpotInstancePools, &out.SpotInstancePools
		*out = new(int64)
		**out = **in
	}
	if in.SpotMaxPrice != nil {
		in, out := &in.SpotMaxPrice, &out.SpotMaxPrice
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancesDistribution.
func (in *InstancesDistribution) DeepCopy() *InstancesDistribution {
	if in == nil {
		return nil
	}
	out := new(InstancesDistribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchConfiguration) DeepCopyInto(out *LaunchConfiguration) {
	*out = *in
	if in.ClassicLinkVPCID != nil {
		in, out := &in.ClassicLinkVPCID, &out.ClassicLinkVPCID
		*out = new(string)
		**out = **in
	}
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.IAMInstanceProfile != nil {
		in, out := &in.IAMInstanceProfile, &out.IAMInstanceProfile
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.InstanceType != nil {
		in, out := &in.InstanceType, &out.InstanceType
		*out = new(string)
		**out = **in
	}
	if in.KernelID != nil {
		in, out := &in.KernelID, &out.KernelID
		*out = new(string)
		**out = **in
	}
	if in.KeyName != nil {
		in, out := &in.KeyName, &out.KeyName
		*out = new(string)
		**out = **in
	}
	if in.LaunchConfigurationARN != nil {
		in, out := &in.LaunchConfigurationARN, &out.LaunchConfigurationARN
		*out = new(string)
		**out = **in
	}
	if in.LaunchConfigurationName != nil {
		in, out := &in.LaunchConfigurationName, &out.LaunchConfigurationName
		*out = new(string)
		**out = **in
	}
	if in.RAMDiskID != nil {
		in, out := &in.RAMDiskID, &out.RAMDiskID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchConfiguration.
func (in *LaunchConfiguration) DeepCopy() *LaunchConfiguration {
	if in == nil {
		return nil
	}
	out := new(LaunchConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchTemplate) DeepCopyInto(out *LaunchTemplate) {
	*out = *in
	if in.LaunchTemplateSpecification != nil {
		in, out := &in.LaunchTemplateSpecification, &out.LaunchTemplateSpecification
		*out = new(LaunchTemplateSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]*LaunchTemplateOverrides, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(LaunchTemplateOverrides)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchTemplate.
func (in *LaunchTemplate) DeepCopy() *LaunchTemplate {
	if in == nil {
		return nil
	}
	out := new(LaunchTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchTemplateOverrides) DeepCopyInto(out *LaunchTemplateOverrides) {
	*out = *in
	if in.InstanceRequirements != nil {
		in, out := &in.InstanceRequirements, &out.InstanceRequirements
		*out = new(InstanceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceType != nil {
		in, out := &in.InstanceType, &out.InstanceType
		*out = new(string)
		**out = **in
	}
	if in.LaunchTemplateSpecification != nil {
		in, out := &in.LaunchTemplateSpecification, &out.LaunchTemplateSpecification
		*out = new(LaunchTemplateSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.WeightedCapacity != nil {
		in, out := &in.WeightedCapacity, &out.WeightedCapacity
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchTemplateOverrides.
func (in *LaunchTemplateOverrides) DeepCopy() *LaunchTemplateOverrides {
	if in == nil {
		return nil
	}
	out := new(LaunchTemplateOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchTemplateSpecification) DeepCopyInto(out *LaunchTemplateSpecification) {
	*out = *in
	if in.LaunchTemplateID != nil {
		in, out := &in.LaunchTemplateID, &out.LaunchTemplateID
		*out = new(string)
		**out = **in
	}
	if in.LaunchTemplateName != nil {
		in, out := &in.LaunchTemplateName, &out.LaunchTemplateName
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchTemplateSpecification.
func (in *LaunchTemplateSpecification) DeepCopy() *LaunchTemplateSpecification {
	if in == nil {
		return nil
	}
	out := new(LaunchTemplateSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleHook) DeepCopyInto(out *LifecycleHook) {
	*out = *in
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.DefaultResult != nil {
		in, out := &in.DefaultResult, &out.DefaultResult
		*out = new(string)
		**out = **in
	}
	if in.HeartbeatTimeout != nil {
		in, out := &in.HeartbeatTimeout, &out.HeartbeatTimeout
		*out = new(int64)
		**out = **in
	}
	if in.LifecycleHookName != nil {
		in, out := &in.LifecycleHookName, &out.LifecycleHookName
		*out = new(string)
		**out = **in
	}
	if in.LifecycleTransition != nil {
		in, out := &in.LifecycleTransition, &out.LifecycleTransition
		*out = new(string)
		**out = **in
	}
	if in.NotificationMetadata != nil {
		in, out := &in.NotificationMetadata, &out.NotificationMetadata
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetARN != nil {
		in, out := &in.NotificationTargetARN, &out.NotificationTargetARN
		*out = new(string)
		**out = **in
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleHook.
func (in *LifecycleHook) DeepCopy() *LifecycleHook {
	if in == nil {
		return nil
	}
	out := new(LifecycleHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleHookSpecification) DeepCopyInto(out *LifecycleHookSpecification) {
	*out = *in
	if in.DefaultResult != nil {
		in, out := &in.DefaultResult, &out.DefaultResult
		*out = new(string)
		**out = **in
	}
	if in.HeartbeatTimeout != nil {
		in, out := &in.HeartbeatTimeout, &out.HeartbeatTimeout
		*out = new(int64)
		**out = **in
	}
	if in.LifecycleHookName != nil {
		in, out := &in.LifecycleHookName, &out.LifecycleHookName
		*out = new(string)
		**out = **in
	}
	if in.LifecycleTransition != nil {
		in, out := &in.LifecycleTransition, &out.LifecycleTransition
		*out = new(string)
		**out = **in
	}
	if in.NotificationMetadata != nil {
		in, out := &in.NotificationMetadata, &out.NotificationMetadata
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetARN != nil {
		in, out := &in.NotificationTargetARN, &out.NotificationTargetARN
		*out = new(string)
		**out = **in
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleHookSpecification.
func (in *LifecycleHookSpecification) DeepCopy() *LifecycleHookSpecification {
	if in == nil {
		return nil
	}
	out := new(LifecycleHookSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerState) DeepCopyInto(out *LoadBalancerState) {
	*out = *in
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerState.
func (in *LoadBalancerState) DeepCopy() *LoadBalancerState {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerTargetGroupState) DeepCopyInto(out *LoadBalancerTargetGroupState) {
	*out = *in
	if in.LoadBalancerTargetGroupARN != nil {
		in, out := &in.LoadBalancerTargetGroupARN, &out.LoadBalancerTargetGroupARN
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerTargetGroupState.
func (in *LoadBalancerTargetGroupState) DeepCopy() *LoadBalancerTargetGroupState {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerTargetGroupState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryGiBPerVCPURequest) DeepCopyInto(out *MemoryGiBPerVCPURequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryGiBPerVCPURequest.
func (in *MemoryGiBPerVCPURequest) DeepCopy() *MemoryGiBPerVCPURequest {
	if in == nil {
		return nil
	}
	out := new(MemoryGiBPerVCPURequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryMiBRequest) DeepCopyInto(out *MemoryMiBRequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryMiBRequest.
func (in *MemoryMiBRequest) DeepCopy() *MemoryMiBRequest {
	if in == nil {
		return nil
	}
	out := new(MemoryMiBRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricCollectionType) DeepCopyInto(out *MetricCollectionType) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricCollectionType.
func (in *MetricCollectionType) DeepCopy() *MetricCollectionType {
	if in == nil {
		return nil
	}
	out := new(MetricCollectionType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricDataQuery) DeepCopyInto(out *MetricDataQuery) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricDataQuery.
func (in *MetricDataQuery) DeepCopy() *MetricDataQuery {
	if in == nil {
		return nil
	}
	out := new(MetricDataQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricGranularityType) DeepCopyInto(out *MetricGranularityType) {
	*out = *in
	if in.Granularity != nil {
		in, out := &in.Granularity, &out.Granularity
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricGranularityType.
func (in *MetricGranularityType) DeepCopy() *MetricGranularityType {
	if in == nil {
		return nil
	}
	out := new(MetricGranularityType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixedInstancesPolicy) DeepCopyInto(out *MixedInstancesPolicy) {
	*out = *in
	if in.InstancesDistribution != nil {
		in, out := &in.InstancesDistribution, &out.InstancesDistribution
		*out = new(InstancesDistribution)
		(*in).DeepCopyInto(*out)
	}
	if in.LaunchTemplate != nil {
		in, out := &in.LaunchTemplate, &out.LaunchTemplate
		*out = new(LaunchTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixedInstancesPolicy.
func (in *MixedInstancesPolicy) DeepCopy() *MixedInstancesPolicy {
	if in == nil {
		return nil
	}
	out := new(MixedInstancesPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkBandwidthGbpsRequest) DeepCopyInto(out *NetworkBandwidthGbpsRequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkBandwidthGbpsRequest.
func (in *NetworkBandwidthGbpsRequest) DeepCopy() *NetworkBandwidthGbpsRequest {
	if in == nil {
		return nil
	}
	out := new(NetworkBandwidthGbpsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceCountRequest) DeepCopyInto(out *NetworkInterfaceCountRequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceCountRequest.
func (in *NetworkInterfaceCountRequest) DeepCopy() *NetworkInterfaceCountRequest {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceCountRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfiguration) DeepCopyInto(out *NotificationConfiguration) {
	*out = *in
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.NotificationType != nil {
		in, out := &in.NotificationType, &out.NotificationType
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfiguration.
func (in *NotificationConfiguration) DeepCopy() *NotificationConfiguration {
	if in == nil {
		return nil
	}
	out := new(NotificationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredefinedMetricSpecification) DeepCopyInto(out *PredefinedMetricSpecification) {
	*out = *in
	if in.ResourceLabel != nil {
		in, out := &in.ResourceLabel, &out.ResourceLabel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredefinedMetricSpecification.
func (in *PredefinedMetricSpecification) DeepCopy() *PredefinedMetricSpecification {
	if in == nil {
		return nil
	}
	out := new(PredefinedMetricSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingPredefinedLoadMetric) DeepCopyInto(out *PredictiveScalingPredefinedLoadMetric) {
	*out = *in
	if in.ResourceLabel != nil {
		in, out := &in.ResourceLabel, &out.ResourceLabel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingPredefinedLoadMetric.
func (in *PredictiveScalingPredefinedLoadMetric) DeepCopy() *PredictiveScalingPredefinedLoadMetric {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingPredefinedLoadMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingPredefinedMetricPair) DeepCopyInto(out *PredictiveScalingPredefinedMetricPair) {
	*out = *in
	if in.ResourceLabel != nil {
		in, out := &in.ResourceLabel, &out.ResourceLabel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingPredefinedMetricPair.
func (in *PredictiveScalingPredefinedMetricPair) DeepCopy() *PredictiveScalingPredefinedMetricPair {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingPredefinedMetricPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingPredefinedScalingMetric) DeepCopyInto(out *PredictiveScalingPredefinedScalingMetric) {
	*out = *in
	if in.ResourceLabel != nil {
		in, out := &in.ResourceLabel, &out.ResourceLabel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingPredefinedScalingMetric.
func (in *PredictiveScalingPredefinedScalingMetric) DeepCopy() *PredictiveScalingPredefinedScalingMetric {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingPredefinedScalingMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessType) DeepCopyInto(out *ProcessType) {
	*out = *in
	if in.ProcessName != nil {
		in, out := &in.ProcessName, &out.ProcessName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessType.
func (in *ProcessType) DeepCopy() *ProcessType {
	if in == nil {
		return nil
	}
	out := new(ProcessType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackDetails) DeepCopyInto(out *RollbackDetails) {
	*out = *in
	if in.RollbackReason != nil {
		in, out := &in.RollbackReason, &out.RollbackReason
		*out = new(string)
		**out = **in
	}
	if in.RollbackStartTime != nil {
		in, out := &in.RollbackStartTime, &out.RollbackStartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackDetails.
func (in *RollbackDetails) DeepCopy() *RollbackDetails {
	if in == nil {
		return nil
	}
	out := new(RollbackDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingPolicy) DeepCopyInto(out *ScalingPolicy) {
	*out = *in
	if in.AdjustmentType != nil {
		in, out := &in.AdjustmentType, &out.AdjustmentType
		*out = new(string)
		**out = **in
	}
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(int64)
		**out = **in
	}
	if in.MetricAggregationType != nil {
		in, out := &in.MetricAggregationType, &out.MetricAggregationType
		*out = new(string)
		**out = **in
	}
	if in.PolicyARN != nil {
		in, out := &in.PolicyARN, &out.PolicyARN
		*out = new(string)
		**out = **in
	}
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingPolicy.
func (in *ScalingPolicy) DeepCopy() *ScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledUpdateGroupAction) DeepCopyInto(out *ScheduledUpdateGroupAction) {
	*out = *in
	if in.AutoScalingGroupName != nil {
		in, out := &in.AutoScalingGroupName, &out.AutoScalingGroupName
		*out = new(string)
		**out = **in
	}
	if in.DesiredCapacity != nil {
		in, out := &in.DesiredCapacity, &out.DesiredCapacity
		*out = new(int64)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int64)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(int64)
		**out = **in
	}
	if in.Recurrence != nil {
		in, out := &in.Recurrence, &out.Recurrence
		*out = new(string)
		**out = **in
	}
	if in.ScheduledActionARN != nil {
		in, out := &in.ScheduledActionARN, &out.ScheduledActionARN
		*out = new(string)
		**out = **in
	}
	if in.ScheduledActionName != nil {
		in, out := &in.ScheduledActionName, &out.ScheduledActionName
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledUpdateGroupAction.
func (in *ScheduledUpdateGroupAction) DeepCopy() *ScheduledUpdateGroupAction {
	if in == nil {
		return nil
	}
	out := new(ScheduledUpdateGroupAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledUpdateGroupActionRequest) DeepCopyInto(out *ScheduledUpdateGroupActionRequest) {
	*out = *in
	if in.DesiredCapacity != nil {
		in, out := &in.DesiredCapacity, &out.DesiredCapacity
		*out = new(int64)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int64)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(int64)
		**out = **in
	}
	if in.Recurrence != nil {
		in, out := &in.Recurrence, &out.Recurrence
		*out = new(string)
		**out = **in
	}
	if in.ScheduledActionName != nil {
		in, out := &in.ScheduledActionName, &out.ScheduledActionName
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledUpdateGroupActionRequest.
func (in *ScheduledUpdateGroupActionRequest) DeepCopy() *ScheduledUpdateGroupActionRequest {
	if in == nil {
		return nil
	}
	out := new(ScheduledUpdateGroupActionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspendedProcess) DeepCopyInto(out *SuspendedProcess) {
	*out = *in
	if in.ProcessName != nil {
		in, out := &in.ProcessName, &out.ProcessName
		*out = new(string)
		**out = **in
	}
	if in.SuspensionReason != nil {
		in, out := &in.SuspensionReason, &out.SuspensionReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspendedProcess.
func (in *SuspendedProcess) DeepCopy() *SuspendedProcess {
	if in == nil {
		return nil
	}
	out := new(SuspendedProcess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.PropagateAtLaunch != nil {
		in, out := &in.PropagateAtLaunch, &out.PropagateAtLaunch
		*out = new(bool)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagDescription) DeepCopyInto(out *TagDescription) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.PropagateAtLaunch != nil {
		in, out := &in.PropagateAtLaunch, &out.PropagateAtLaunch
		*out = new(bool)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagDescription.
func (in *TagDescription) DeepCopy() *TagDescription {
	if in == nil {
		return nil
	}
	out := new(TagDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetTrackingMetricDataQuery) DeepCopyInto(out *TargetTrackingMetricDataQuery) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetTrackingMetricDataQuery.
func (in *TargetTrackingMetricDataQuery) DeepCopy() *TargetTrackingMetricDataQuery {
	if in == nil {
		return nil
	}
	out := new(TargetTrackingMetricDataQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TotalLocalStorageGBRequest) DeepCopyInto(out *TotalLocalStorageGBRequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TotalLocalStorageGBRequest.
func (in *TotalLocalStorageGBRequest) DeepCopy() *TotalLocalStorageGBRequest {
	if in == nil {
		return nil
	}
	out := new(TotalLocalStorageGBRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficSourceIdentifier) DeepCopyInto(out *TrafficSourceIdentifier) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficSourceIdentifier.
func (in *TrafficSourceIdentifier) DeepCopy() *TrafficSourceIdentifier {
	if in == nil {
		return nil
	}
	out := new(TrafficSourceIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficSourceState) DeepCopyInto(out *TrafficSourceState) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.TrafficSource != nil {
		in, out := &in.TrafficSource, &out.TrafficSource
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficSourceState.
func (in *TrafficSourceState) DeepCopy() *TrafficSourceState {
	if in == nil {
		return nil
	}
	out := new(TrafficSourceState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCPUCountRequest) DeepCopyInto(out *VCPUCountRequest) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCPUCountRequest.
func (in *VCPUCountRequest) DeepCopy() *VCPUCountRequest {
	if in == nil {
		return nil
	}
	out := new(VCPUCountRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmPoolConfiguration) DeepCopyInto(out *WarmPoolConfiguration) {
	*out = *in
	if in.InstanceReusePolicy != nil {
		in, out := &in.InstanceReusePolicy, &out.InstanceReusePolicy
		*out = new(InstanceReusePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxGroupPreparedCapacity != nil {
		in, out := &in.MaxGroupPreparedCapacity, &out.MaxGroupPreparedCapacity
		*out = new(int64)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(int64)
		**out = **in
	}
	if in.PoolState != nil {
		in, out := &in.PoolState, &out.PoolState
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmPoolConfiguration.
func (in *WarmPoolConfiguration) DeepCopy() *WarmPoolConfiguration {
	if in == nil {
		return nil
	}
	out := new(WarmPoolConfiguration)
	in.DeepCopyInto(out)
	return out
}
