/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package key

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/kms"
	svcsdk "github.com/aws/aws-sdk-go/service/kms"
	svcsdkapi "github.com/aws/aws-sdk-go/service/kms/kmsiface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane/provider-aws/apis/kms/v1alpha1"
	awsclient "github.com/crossplane/provider-aws/pkg/clients"
)

const (
	errUnexpectedObject = "managed resource is not an Key resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create Key in AWS"
	errUpdate        = "cannot update Key in AWS"
	errDescribe      = "failed to describe Key"
	errDelete        = "failed to delete Key"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.Key)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := awsclient.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.Key)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateDescribeKeyInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.DescribeKeyWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateKey(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)

	upToDate, err := e.isUpToDate(cr, resp)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.Key)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateKeyInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateKeyWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}

	if resp.KeyMetadata.AWSAccountId != nil {
		cr.Status.AtProvider.AWSAccountID = resp.KeyMetadata.AWSAccountId
	} else {
		cr.Status.AtProvider.AWSAccountID = nil
	}
	if resp.KeyMetadata.Arn != nil {
		cr.Status.AtProvider.ARN = resp.KeyMetadata.Arn
	} else {
		cr.Status.AtProvider.ARN = nil
	}
	if resp.KeyMetadata.CloudHsmClusterId != nil {
		cr.Status.AtProvider.CloudHsmClusterID = resp.KeyMetadata.CloudHsmClusterId
	} else {
		cr.Status.AtProvider.CloudHsmClusterID = nil
	}
	if resp.KeyMetadata.CreationDate != nil {
		cr.Status.AtProvider.CreationDate = &metav1.Time{*resp.KeyMetadata.CreationDate}
	} else {
		cr.Status.AtProvider.CreationDate = nil
	}
	if resp.KeyMetadata.CustomKeyStoreId != nil {
		cr.Spec.ForProvider.CustomKeyStoreID = resp.KeyMetadata.CustomKeyStoreId
	} else {
		cr.Spec.ForProvider.CustomKeyStoreID = nil
	}
	if resp.KeyMetadata.CustomerMasterKeySpec != nil {
		cr.Spec.ForProvider.CustomerMasterKeySpec = resp.KeyMetadata.CustomerMasterKeySpec
	} else {
		cr.Spec.ForProvider.CustomerMasterKeySpec = nil
	}
	if resp.KeyMetadata.DeletionDate != nil {
		cr.Status.AtProvider.DeletionDate = &metav1.Time{*resp.KeyMetadata.DeletionDate}
	} else {
		cr.Status.AtProvider.DeletionDate = nil
	}
	if resp.KeyMetadata.Description != nil {
		cr.Spec.ForProvider.Description = resp.KeyMetadata.Description
	} else {
		cr.Spec.ForProvider.Description = nil
	}
	if resp.KeyMetadata.Enabled != nil {
		cr.Status.AtProvider.Enabled = resp.KeyMetadata.Enabled
	} else {
		cr.Status.AtProvider.Enabled = nil
	}
	if resp.KeyMetadata.EncryptionAlgorithms != nil {
		f9 := []*string{}
		for _, f9iter := range resp.KeyMetadata.EncryptionAlgorithms {
			var f9elem string
			f9elem = *f9iter
			f9 = append(f9, &f9elem)
		}
		cr.Status.AtProvider.EncryptionAlgorithms = f9
	} else {
		cr.Status.AtProvider.EncryptionAlgorithms = nil
	}
	if resp.KeyMetadata.ExpirationModel != nil {
		cr.Status.AtProvider.ExpirationModel = resp.KeyMetadata.ExpirationModel
	} else {
		cr.Status.AtProvider.ExpirationModel = nil
	}
	if resp.KeyMetadata.KeyId != nil {
		cr.Status.AtProvider.KeyID = resp.KeyMetadata.KeyId
	} else {
		cr.Status.AtProvider.KeyID = nil
	}
	if resp.KeyMetadata.KeyManager != nil {
		cr.Status.AtProvider.KeyManager = resp.KeyMetadata.KeyManager
	} else {
		cr.Status.AtProvider.KeyManager = nil
	}
	if resp.KeyMetadata.KeySpec != nil {
		cr.Spec.ForProvider.KeySpec = resp.KeyMetadata.KeySpec
	} else {
		cr.Spec.ForProvider.KeySpec = nil
	}
	if resp.KeyMetadata.KeyState != nil {
		cr.Status.AtProvider.KeyState = resp.KeyMetadata.KeyState
	} else {
		cr.Status.AtProvider.KeyState = nil
	}
	if resp.KeyMetadata.KeyUsage != nil {
		cr.Spec.ForProvider.KeyUsage = resp.KeyMetadata.KeyUsage
	} else {
		cr.Spec.ForProvider.KeyUsage = nil
	}
	if resp.KeyMetadata.MultiRegion != nil {
		cr.Spec.ForProvider.MultiRegion = resp.KeyMetadata.MultiRegion
	} else {
		cr.Spec.ForProvider.MultiRegion = nil
	}
	if resp.KeyMetadata.MultiRegionConfiguration != nil {
		f17 := &svcapitypes.MultiRegionConfiguration{}
		if resp.KeyMetadata.MultiRegionConfiguration.MultiRegionKeyType != nil {
			f17.MultiRegionKeyType = resp.KeyMetadata.MultiRegionConfiguration.MultiRegionKeyType
		}
		if resp.KeyMetadata.MultiRegionConfiguration.PrimaryKey != nil {
			f17f1 := &svcapitypes.MultiRegionKey{}
			if resp.KeyMetadata.MultiRegionConfiguration.PrimaryKey.Arn != nil {
				f17f1.ARN = resp.KeyMetadata.MultiRegionConfiguration.PrimaryKey.Arn
			}
			if resp.KeyMetadata.MultiRegionConfiguration.PrimaryKey.Region != nil {
				f17f1.Region = resp.KeyMetadata.MultiRegionConfiguration.PrimaryKey.Region
			}
			f17.PrimaryKey = f17f1
		}
		if resp.KeyMetadata.MultiRegionConfiguration.ReplicaKeys != nil {
			f17f2 := []*svcapitypes.MultiRegionKey{}
			for _, f17f2iter := range resp.KeyMetadata.MultiRegionConfiguration.ReplicaKeys {
				f17f2elem := &svcapitypes.MultiRegionKey{}
				if f17f2iter.Arn != nil {
					f17f2elem.ARN = f17f2iter.Arn
				}
				if f17f2iter.Region != nil {
					f17f2elem.Region = f17f2iter.Region
				}
				f17f2 = append(f17f2, f17f2elem)
			}
			f17.ReplicaKeys = f17f2
		}
		cr.Status.AtProvider.MultiRegionConfiguration = f17
	} else {
		cr.Status.AtProvider.MultiRegionConfiguration = nil
	}
	if resp.KeyMetadata.Origin != nil {
		cr.Spec.ForProvider.Origin = resp.KeyMetadata.Origin
	} else {
		cr.Spec.ForProvider.Origin = nil
	}
	if resp.KeyMetadata.PendingDeletionWindowInDays != nil {
		cr.Status.AtProvider.PendingDeletionWindowInDays = resp.KeyMetadata.PendingDeletionWindowInDays
	} else {
		cr.Status.AtProvider.PendingDeletionWindowInDays = nil
	}
	if resp.KeyMetadata.SigningAlgorithms != nil {
		f20 := []*string{}
		for _, f20iter := range resp.KeyMetadata.SigningAlgorithms {
			var f20elem string
			f20elem = *f20iter
			f20 = append(f20, &f20elem)
		}
		cr.Status.AtProvider.SigningAlgorithms = f20
	} else {
		cr.Status.AtProvider.SigningAlgorithms = nil
	}
	if resp.KeyMetadata.ValidTo != nil {
		cr.Status.AtProvider.ValidTo = &metav1.Time{*resp.KeyMetadata.ValidTo}
	} else {
		cr.Status.AtProvider.ValidTo = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	return e.update(ctx, mg)

}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.Key)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	return e.delete(ctx, mg)

}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.KMSAPI, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		delete:         nopDelete,
		update:         nopUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.KMSAPI
	preObserve     func(context.Context, *svcapitypes.Key, *svcsdk.DescribeKeyInput) error
	postObserve    func(context.Context, *svcapitypes.Key, *svcsdk.DescribeKeyOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	lateInitialize func(*svcapitypes.KeyParameters, *svcsdk.DescribeKeyOutput) error
	isUpToDate     func(*svcapitypes.Key, *svcsdk.DescribeKeyOutput) (bool, error)
	preCreate      func(context.Context, *svcapitypes.Key, *svcsdk.CreateKeyInput) error
	postCreate     func(context.Context, *svcapitypes.Key, *svcsdk.CreateKeyOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	delete         func(context.Context, cpresource.Managed) error
	update         func(context.Context, cpresource.Managed) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.Key, *svcsdk.DescribeKeyInput) error {
	return nil
}

func nopPostObserve(_ context.Context, _ *svcapitypes.Key, _ *svcsdk.DescribeKeyOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopLateInitialize(*svcapitypes.KeyParameters, *svcsdk.DescribeKeyOutput) error {
	return nil
}
func alwaysUpToDate(*svcapitypes.Key, *svcsdk.DescribeKeyOutput) (bool, error) {
	return true, nil
}

func nopPreCreate(context.Context, *svcapitypes.Key, *svcsdk.CreateKeyInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.Key, _ *svcsdk.CreateKeyOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopDelete(context.Context, cpresource.Managed) error {
	return nil
}
func nopUpdate(context.Context, cpresource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, nil
}
